### PR TITLE
T187969 Prevent horizontal scrolling on diff

### PR DESCRIPTION
**Pull request by davidbarratt**

### CODE REVIEW

**Review by dayllanmaza — DISMISSED** [review]

**Comment by dayllanmaza** [comment]
screen shot 2018-02-26 at 12 08 37

I approved it earlier but after further testing, Isn't this the same issue? I'm on Firefox Dev Edition 59.0b12 (64-bit)

**Comment by davidbarratt** [comment]
@dayllanmaza Can you give me the URL to your query?

**Comment by dayllanmaza** [comment]
http://127.0.0.1:8888/?wiki=enwiki&user=CSinders%20(WMF)&user=TBolliger%20(WMF)

Strange. I don't get the same revision at that day/time for the same users. :thinking: 
Regardless, here is a screenshot with the horizontal scrolling
screen shot 2018-02-26 at 12 50 03

This is at 1366px width using firefox's responsive design mode

**Comment by davidbarratt** [comment]
@dayllanmaza That should fix the issue.

**Review by dayllanmaza — APPROVED** [review]

**Pull request merged**
