### PR TITLE
T199235 Use ssh tunnel on host machine

### PR DESCRIPTION
**Pull request by davidbarratt**
and @aezell!

### CODE REVIEW

**Comment by davidbarratt** [comment]
I had to create different instructions for Linux because of docker/for-linux#264, which I hope they fix soon!

**Review by MusikAnimal — APPROVED** [review]
Works for me!!! Finally I can contribute to Interaction Timeline! Thank you! :D

**Comment by davidbarratt** [comment]
This should all work on Linux now (I hope!)

**Comment by mooeypoo** [comment]
I tried:
- I fetched the PR
- then made sure to copy the .env.dist to .env
- Copied my ssh key (cp /path/to/your/priv/key ./etc/ssh/id_rsa`)
- Ran docker-compose up

The system works in the sense that I see the site, but all requests fail:

Error 400
An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused
Request URL
/api/enwiki/interaction?user=Mooeypoo|Catrope&start_date=1402012800&end_date=1528329599

This is what I have in the logs:

```
[2018-08-06 19:36:12] app.ERROR: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused ["#0 /var/www/server/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 /var/www/server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\\DBAL\\DBALException::driverException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException))\n#2 /var/www/server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 's53550', 'M3Y0Zwq2hzhzDkb...', Array)\n#3 /var/www/server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\\DBAL\\Connection->connect()\n#4 /var/www/server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): Doctrine\\DBAL\\Connection->executeQuery('SELECT user_id ...', Array, Array)\n#5 /var/www/server/src/Dao/UserDao.php(19): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#6 /var/www/server/src/Service/InteractionService.php(50): App\\Dao\\UserDao->getUserId('Mooeypoo')\n#7 [internal function]: App\\Service\\InteractionService->App\\Service\\{closure}('Mooeypoo')\n#8 /var/www/server/src/Service/InteractionService.php(55): array_map(Object(Closure), Array)\n#9 /var/www/server/src/Action/InteractionAction.php(38): App\\Service\\InteractionService->getInteraction(Array, '1402012800', '1528329599', 50, NULL)\n#10 [internal function]: App\\Action\\InteractionAction->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#11 /var/www/server/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#12 /var/www/server/vendor/slim/slim/Slim/Route.php(335): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#13 /var/www/server/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#14 /var/www/server/vendor/slim/slim/Slim/Route.php(313): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#15 /var/www/server/vendor/slim/slim/Slim/App.php(495): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#16 /var/www/server/src/Middleware/ConnectionManagerMiddleware.php(37): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#17 [internal function]: App\\Middleware\\ConnectionManagerMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#18 /var/www/server/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(App\\Middleware\\ConnectionManagerMiddleware), Array)\n#19 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#20 /var/www/server/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))\n#21 /var/www/server/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#22 /var/www/server/vendor/slim/slim/Slim/App.php(388): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#23 /var/www/server/vendor/slim/slim/Slim/App.php(296): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))\n#24 /var/www/server/public/index.php(15): Slim\\App->run()\n#25 {main}"] []
```

**Comment by davidbarratt** [comment]
```
[15:48:39] davidwbarratt:	mooeypoo you don't need to copy your key anymore. :) but you will need an open tunnel to toolforge in another terminal
[15:49:22] mooeypoo:	Hm I thought it was open, let me retry
[15:52:34] davidwbarratt:	mooeypoo and it also has to be on the same port as what you have in  your .env file
```

**Review by dayllanmaza — CHANGES_REQUESTED** [review]
Not working on linux for me.
```
ssh -N myuser@tools-dev.wmflabs.org -L 3306:enwiki.analytics.db.svc.eqiad.wmflabs:3306
```
I can connect in my local host through mysql cli to 127.0.0.1:3306.

Application gives me connection refused.

.env is configured to use host.docker.internal and 3306


Am I missing something?

**Review by dayllanmaza — APPROVED** [review]

**Comment by dayllanmaza** [comment]
Never mind.. It works. It is worth mentioning that at least on linux you have to bind the tunnel to 0.0.0.0, otherwise it fails. Maybe it should be added to the README.md file

Example
```
ssh -N yourusername@tools-dev.wmflabs.org -L 0.0.0.0:3306:enwiki.analytics.db.svc.eqiad.wmflabs:3306  
```

**Comment by davidbarratt** [comment]
@dayllanmaza haha! I just figured this out as well! :)

**Comment by davidbarratt** [comment]
@dayllanmaza I added that detail to the `README`

**Pull request merged**
