### PR TITLE
Update colors to match Wikimedia UI style guide

### PR DESCRIPTION
**Pull request by prtksxna**
This make as few change as possible to the design while still
being able to use the new colors.

### CODE REVIEW

**Review by aezell — CHANGES_REQUESTED** [review]
There’s a “Copy” button on the modal that comes up after you click “Share this result.” It seems like that blue is probably incorrect. The class is just .btn, .btn-primary which appears to come from bootstrap and not the wikimedia style set.

**Comment by prtksxna** [comment]
## Before
Screenshot 2019-08-15 at 2 21 18 PM

## After
Screenshot 2019-08-15 at 2 21 09 PM

**Comment by prtksxna** [comment]
I couldn't find where `.diff-deletedline` and `.diff-addedline` were on the interface, so I haven't changed their colors yet.

**Comment by prtksxna** [comment]
> There’s a “Copy” button on the modal that comes up after you click “Share this result.” It seems like that blue is probably incorrect. The class is just .btn, .btn-primary which appears to come from bootstrap and not the wikimedia style set.

I think by setting `$primary: #36c;` the bootstrap colors get overridden. The button has the correct [Accent50 color](https://design.wikimedia.org/style-guide/visual-style_colors.html).

**Comment by aezell** [comment]
> > There’s a “Copy” button on the modal that comes up after you click “Share this result.” It seems like that blue is probably incorrect. The class is just .btn, .btn-primary which appears to come from bootstrap and not the wikimedia style set.
> 
> I think by setting `$primary: #36c;` the bootstrap colors get overridden. The button has the correct [Accent50 color](https://design.wikimedia.org/style-guide/visual-style_colors.html).

Perfect. Thanks for checking.

**Review by aezell — APPROVED** [review]

**Comment by davidbarratt** [comment]
The logo colors need to be updated. :)

**Pull request merged**
