### PR TITLE
Disable autocompletion in the form

### PR DESCRIPTION
**Pull request by MusikAnimal**
This disables the browser's autocompletion, which will clash with the live search. I still don't have InteractionTimeline working locally... not sure if I needed to rebuild the JS for this commit, or if that's done when deploying?

### CODE REVIEW

**Comment by dayllanmaza** [comment]
@MusikAnimal did you try adding a key without a passphrase to toolforge and using that one? I'm still to fix that db container to allow a passphrase

**Comment by MusikAnimal** [comment]
> did you try adding a key without a passphrase to toolforge and using that one? I'm still to fix that db container to allow a passphrase

Going to try that now, actually!

**Comment by davidbarratt** [comment]
> not sure if I needed to rebuild the JS for this commit, or if that's done when deploying?

that's done when deploying.

**Review by davidbarratt — APPROVED** [review]
I had to look it up, but it is in fact `autoComplete` https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes although in React 16+, `autocomplete` is also supported https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

**Pull request merged**
