### PR TITLE
Update layout: Make a larger header and narrower content

### PR DESCRIPTION
**Pull request by prtksxna**
This is the first step to moving to the layout in
[T188435](https://phabricator.wikimedia.org/T188435). This can be merged as is, I'll be making
updates on top of this (either in this PR or separately)

### CODE REVIEW

**Comment by prtksxna** [comment]
This is what it looks like with these changes:
Interaction Timeline

**Comment by davidbarratt** [comment]
@prtksxna one of the original design goals was to increase the information density, this appears to be a departure from that. Is that a direction we want to go @Niharika29?

**Comment by prtksxna** [comment]
@davidbarratt, this redesign is purely visual at the moment, from the [old ticket](https://phabricator.wikimedia.org/T188435) and [mockups](https://wikimedia.invisionapp.com/share/VRG4FI7NDJY#/282441034_Landing). I am happy to make changes to this once we do one pass at this. Would that be okay?

**Comment by davidbarratt** [comment]
@prtksxna I have no opinion on the matter, it just seems like the opposite of what was done in https://phabricator.wikimedia.org/T180090

**Comment by prtksxna** [comment]
@davidbarratt, there is more history here than I understand 😅From what I know Nirzar and Trevor agreed on this last year and then #85 got stuck so I am trying to redo it.

**Comment by davidbarratt** [comment]
@prtksxna I'm totally fine doing whatever. :) I just didn't want to revert something without @Niharika29's approval. :)

**Comment by Niharika29** [comment]
I see that these changes were discussed between Trevor and Nirzar on https://phabricator.wikimedia.org/T188435. Let's go ahead and merge. :)

**Comment by prtksxna** [comment]
Hey @davidbarratt, could you take another look at this? I'll keep building off this once merged 😊

**Comment by davidbarratt** [comment]
@prtksxna I've put it on the todo list (err... the workboard): https://phabricator.wikimedia.org/T188435#5496078

**Pull request merged**
